version: '3'

services:

  mysql:
    image: mysql:5
    platform: linux/amd64
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    networks:
      - quizzo

  wordpress:
    image: wordpress
    depends_on:
      - mysql
    ports:
      - 8888:80
    volumes:
      - wp_data:/var/www/html/wp-content
      - .:/var/www/html/wp-content/plugins/quizzo
    restart: always
    environment:
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
    networks:
      - quizzo

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    depends_on:
      - mysql
    ports:
      - 8888:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
    networks:
      - quizzo

volumes:
  db_data: {}
  wp_data: {}

networks:
  quizzo:
